### PR TITLE
Synchronizing with pyproject.toml

### PR DESCRIPTION
**Pull request by michaelcdevin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by michaelcdevin** [comment]
@conda-forge-admin, please rerender

**Comment by michaelcdevin** [comment]
Added python version requirements as well to match `pyproject.toml`, since this was causing linting issues

**Comment by rafa-guedes** [comment]
Thanks for this pull request @michaelcdevin The Windows builds seem to be broken though with these changes.

**Comment by rafa-guedes** [comment]
@michaelcdevin I'm closing this since the typing_extension dependency is no longer an issue.

**Pull request closed without merging**
